# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Car": "00_core.ipynb",
         "IMPORTANT_STRING": "00_core.ipynb",
         "get_car_to_important_location": "01_drive_car.ipynb"}

modules = ["core.py",
           "drive_car.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
