# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Car', 'IMPORTANT_STRING']

# Cell
class Car(object):
    def __init__(self, num_wheels: int = 4, location:str = None):
        self.num_wheels = num_wheels
        self.location = location or 'at home'

    def get_location(self):
        return self.location

    def drive(self, where:str):
        self.location = where
        return f'drove to {self.location}'


# Cell
IMPORTANT_STRING ="Munich"