# AUTOGENERATED! DO NOT EDIT! File to edit: 01_drive_car.ipynb (unless otherwise specified).

__all__ = ['get_car_to_important_location']

# Cell
def get_car_to_important_location(car,location):
    print(car.drive(location))
    return f'car is now at {car.get_location()}'

