# AUTOGENERATED! DO NOT EDIT! File to edit: 02_tests.ipynb (unless otherwise specified).

__all__ = ['test_location']

# Cell
def test_location(location):
    assert type(location) == str, 'looks like the locations isnt a string'